<?php

$GLOBALS['CONFIG'] = array(
	'LOCALE'=>'en_us',
	'MOBILAP_MAJOR_VERSION'=>2,
	'MOBILAP_MINOR_VERSION'=>0,
	'MOBILAP_TERTIARY_VERSION'=>0,
    'SITE_TITLE'=>'mobilAP',
    'CONTENT_PRIVATE'=>false,
    'USE_PASSWORDS'=>true,
    'USE_ADMIN_PASSWORDS'=>true,
    'USE_PRESENTER_PASSWORDS'=>true,
    'ALLOW_SELF_CREATED_USERS'=>false,
    'SINGLE_SESSION_MODE'=>false,
    'THUMB_WIDTH'=>100,
    'THUMB_HEIGHT'=>100
);
    
?>